import { getProduct } from "./api/product";
import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Carousel from "../components/Carousel";
const Home = () => {
  const [data, setData] = React.useState<ProductDTO[]>([]);
  React.useEffect(() => {
    getProduct().then((x) => setData(x || []));
  }, []);
  return (
    <>
      <Head>
        <title>Shopping web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
      <div className={styles.products}>
        {data.map((d) => (
          <>
            <Link href={`product/${d.id}`}>
              <a>
                <div key={d.id} className={styles.card}>
                  <div className={styles.img_product}>
                    <Image
                      src={d.images[0]}
                      alt="product img"
                      width={200}
                      height={150}
                    />
                  </div>
                  <div className="card-body">
                    <h5 className={styles.card_title}>{d.title}</h5>
                    <p className={styles.description}>{d.description}</p>
                    <h5 className="text-danger">฿{d.price}</h5>
                  </div>
                </div>
              </a>
            </Link>
          </>
        ))}
      </div>
    </>
  );
};

export default Home;
